accounts/urls.py
from django.urls import path
from .views import user_login, logout, signup

urlpatterns = [
    path("login/", user_login, name="login"),
    path("signup/", signup, name="signup"),
    path("logout/", logout, name="logout"),
]

projects/urls.py
from django.urls import path
from .views import project_list

urlpatterns = [
    path("", project_list, name="project_list"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import signup

from django.shortcuts import redirect


def redirect_to_project_list(request):
    return redirect("project_list")


urlpatterns = [
    path("", redirect_to_project_list, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("accounts/signup/", signup, name="signup"),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, null=True, related_name="tasks", on_delete=models.CASCADE
    )

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    password_confirmation = forms.CharField(
        max_length=150, widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = (
            "username",
            "password1",
            "password2",
            "password_confirmation",
        )


class LogInForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput())

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from accounts.forms import LogInForm
from .forms import SignupForm
from django.contrib.auth.models import User


def user_logout(request):
    logout(request)
    return redirect("accounts:login")


def user_login(request):
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("project_list")
    else:
        form = LogInForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]
            if password != password_confirmation:
                error_message = "The passwords do not match"
                return render(
                    request,
                    "registration/signup.html",
                    {"form": form, "error_message": error_message},
                )
            if User.objects.filter(username=username).exists():
                error_message = "The username is already taken"
                return render(
                    request,
                    "registration/signup.html",
                    {"form": form, "error_message": error_message},
                )
            user = User.objects.create_user(
                username=username, password=password
            )
            login(request, user)
            return redirect("project_list")
    else:
        form = SignupForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Project


@login_required
class ProjectListView(ListView):
    model = Project
    template_name = "project_list.html"
    context_object_name = "projects"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(members=self.request.user)


@login_required
def redirect_to_project_list(request):
    return redirect("project_list")


@login_required
def project_list(request):
    projects = Project.objects.filter(members=request.user)
    return render(
        request, "projects/project_list.html", {"projects": projects}
    )


@login_required
def home(request):
    projects = Project.objects.filter(members=request.user)
    context = {"projects": projects}
    return render(request, "projects/home.html", context)

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div>
            <h1>Login</h1>
            <form method="post">
                {{ form.as_p }}
                <button>Login</button>
            </form>
        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h1>Signup</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_username">Username:</label>
            <input type="text" name="username" maxlength="150" required>
            <br>
            <label for="id_password">Password:</label>
            <input type="password" name="password" maxlength="150" required>
            <br>
            <label for="id_password_confirmation">Confirm Password:</label>
            <input type="password" name="password_confirmation" maxlength="150" required>
            <br>
            <button type="submit">Signup</button>
        </form>
        {% if error_message %}<p>{{ error_message }}</p>{% endif %}
    </div>
{% endblock content %}

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>List of Receipts</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <form>
                    {% block content %}
                    {% endblock content %}
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Project List</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'project_list' %}">Projects</a>
                    </li>
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Projects</h1>
                {% if projects %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in projects %}
                                <tr>
                                    <td>{{ project.num_tasks }}</td>
                                    <td></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You are not assigned to any projects.</p>
                {% endif %}
            </div>
        </main>
        <footer>
            <p>thanks for visiting</p>
        </footer>
    </body>
</html>

projects/templates/projects/project_list.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h1>My Projects</h1>
        {% if projects %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in projects %}
                        <tr>
                            <td>{{ project.name }}</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You are not assigned to any projects</p>
        {% endif %}
    </div>
{% endblock content %}